CREATE TABLE  IF NOT EXISTS stockquote
(
id  SERIAL PRIMARY KEY ,
currentPrice DOUBLE PRECISION,
changePrice DOUBLE PRECISION,
changePercent DOUBLE PRECISION,
highPriceDay DOUBLE PRECISION,
lowPriceDay DOUBLE PRECISION,
openPriceDay DOUBLE PRECISION,
previousClose DOUBLE PRECISION
);

ALTER TABLE your_table_name
ADD COLUMN stocktime TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN  created_at DEFAULT CURRENT_TIME;
