# Generated by Django 5.2.5 on 2025-09-01 01:46

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPrice', models.FloatField()),
                ('changePrice', models.FloatField()),
                ('changePercent', models.FloatField()),
                ('highPriceDay', models.FloatField()),
                ('lowPriceDay', models.FloatField()),
                ('openPriceDay', models.FloatField()),
                ('previousClose', models.FloatField()),
                ('stocktime', models.DateTimeField(blank=True, default=django.db.models.functions.datetime.Now, null=True)),
                ('stockSymbol', models.CharField(blank=True, default='AAPL', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stockquote',
            },
        ),
    ]
