# Generated by Django 5.2.5 on 2025-09-01 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockquote',
            name='stockSymbol',
            field=models.CharField(max_length=100),
        ),
    ]
