# Generated by Django 5.2.5 on 2025-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stockquote_stocksymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockSymbol', models.CharField(max_length=100)),
                ('highPriceDay', models.FloatField()),
                ('lowPriceDay', models.FloatField()),
                ('openPriceDay', models.FloatField()),
                ('closePriceDay', models.FloatField()),
                ('volume', models.FloatField()),
                ('TradeDate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'HistoricalStockQuote',
            },
        ),
    ]
