# Generated by Django 5.2.5 on 2025-09-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_historicalstockquote'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalstockquote',
            table='historicalStockQuote',
        ),
    ]
