# Generated by Django 5.2.5 on 2025-09-03 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_historicalstockquote_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historicalstockquote',
            table='historicalstockquote',
        ),
    ]
