# Generated by Django 5.2.5 on 2025-09-05 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_historicalstockquote_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstockquote',
            old_name='closePriceDay',
            new_name='close_price_day',
        ),
        migrations.RenameField(
            model_name='historicalstockquote',
            old_name='highPriceDay',
            new_name='high_price_day',
        ),
        migrations.RenameField(
            model_name='historicalstockquote',
            old_name='lowPriceDay',
            new_name='low_price_day',
        ),
        migrations.RenameField(
            model_name='historicalstockquote',
            old_name='openPriceDay',
            new_name='open_price_day',
        ),
        migrations.RenameField(
            model_name='historicalstockquote',
            old_name='stockSymbol',
            new_name='stock_symbol',
        ),
        migrations.RenameField(
            model_name='historicalstockquote',
            old_name='TradeDate',
            new_name='trade_date',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='changePercent',
            new_name='change_percent',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='changePrice',
            new_name='change_price',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='currentPrice',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='highPriceDay',
            new_name='high_price_day',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='lowPriceDay',
            new_name='low_price_day',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='openPriceDay',
            new_name='open_price_day',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='previousClose',
            new_name='previous_close',
        ),
        migrations.RenameField(
            model_name='stockquote',
            old_name='stockSymbol',
            new_name='stock_symbol',
        ),
    ]
